name: Test python-env-action

on: [push]

jobs:
  test-python-env:
    strategy:
      matrix:
        requirements: ['requirements.txt', 'requests numpy']
        constraints: ['constraints.txt', 'requests==2.31 numpy==1.25']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: lucastrschneider/python-env-action@main
      with:
        python-version: 3.11.0
        requirements: ${{ matrix.requirements }}
        constraints: ${{ matrix.constraints }}
        command: python3 main.py